### ISSUE TITLE
Code for filtering data

### ISSUE THREAD

**Issue by laiviet** [microsoft/rho#1]
Seems like the repo only includes some outputs from the model.
Training code/data are excluded. 
Do the authors plan to publish them?

**Comment by ZubinGou** [comment]
Hi @laiviet , thank you for your interest!
We have very strict internal review requirements for releasing data, so it is unlikely to be made available in the short term. However, we plan to release the code once it passes the approval process. The implementation of selective language modeling is quite straightforward, requiring only a few lines of code for scoring and selection. If you encounter any issues, please feel free to contact me and @lzh0525.

**Comment by a1789591** [comment]
Hi Zubin,
Can you share the implementation for SLM and token selection now? It would be better to have your code to understand your work in detail.
